# Generated by Django 6.0.4 on 2026-05-04 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_tatuagens', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='estilo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='tatuador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='app_gestao_tatuagens.tatuador'),
        ),
    ]
