# Generated by Django 6.0.4 on 2026-05-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_tatuagens', '0005_portfolio_destaque_portfolio_estilo_portfolio_titulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.RemoveField(
            model_name='servico',
            name='duracao',
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duração estimada do serviço em minutos'),
        ),
    ]
